modified chat events tests so they no longer fail if not skipped
symbiont-io/sympl_chat pull request #8
Opened 2021-09-13 21:18 UTC by symbiont-david-bono

2021-09-14 07:21 UTC, symbiont-aurelien-bonnel requested changes

2021-09-14 07:21 UTC, symbiont-aurelien-bonnel commented on test/chat_8_3_0_0_events_test.py
> +        print("\n\n\n\n\n\n")
Presumably that's not needed?

2021-09-14 14:55 UTC, symbiont-david-bono commented on test/chat_8_3_0_0_events_test.py
> +        print("\n\n\n\n\n\n")
Oops!

2021-09-14 17:38 UTC, symbiont-jason-skophammer approved these changes
Looks good to me

2021-09-15 07:52 UTC, symbiont-aurelien-bonnel approved these changes

2021-09-15 11:40 UTC, merged